app:
  timezone: "UTC"
  logging:
    log_dir: "logs"
    runner_log: "hourly_runner.log"

paths:
  db_path: "data/crypto_data.db"
  log_path: "logs/hourly_runner.log"

binance:
  # 实际key/secret存放在 .env 中，yaml 里只留占位；真正加载时允许 env 覆盖
  api_key: "${B_KEY}"
  api_secret: "${B_SECRET}"
  proxy_env: "proxy.env"
  api_env: "binance_api.env"
  http_proxy: "${binance_proxy}"

data:
  interval: "1h"
  start_delta_days: 60
  model_start_from_now: true  # 以 NOW-60d 作为训练数据起点
  symbols:
    target: "ETHUSDT"
    load_symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "DOGEUSDT"]

features:
  other_symbols: ["BTCUSDT","ETHUSDT","SOLUSDT","DOGEUSDT"]
  lags: [1,2,4,12,24,48,72]
  rt_targets: [1,2,4,12,24]
  vol_window: 24
  rsi_window: 12
  mfi_window: 12
  bb_window: 24
  tema_windows: [12,24,36]
  adx_window: 12
  cmo_window: 12
  ulti_os_windows: { period1: 8, period2: 12, period3: 24 }
  patterns:
    CDLENGULFING: "吞没形态"
    CDLHAMMER: "锤子线"
    CDLHANGINGMAN: "吊人线"
    CDLDOJI: "十字星"
    CDLDRAGONFLYDOJI: "蜻蜓十字星"
    CDLGRAVESTONEDOJI: "墓碑十字星"
    CDLMORNINGSTAR: "晨星"
    CDLEVENINGSTAR: "暮星"
    CDLSHOOTINGSTAR: "流星"
    CDLMARUBOZU: "光头光脚"

feature_process:
  metrics_to_scale: ["high","low","close"]
  cols_to_drop: ["open","high","low","close","volume","dollar_vol","hour","atr","macdhist","hour_bin_label","cmo","tema_12","tema_24","tema_36"]

cv:
  train_length: 672    # 24*7*4
  test_length: 1
  lookahead: 1
  date_idx: "datetime"

model:
  name: "rf-reg"
  type: "RandomForestRegressor"
  params:
    n_estimators: 300
    min_samples_leaf: 7
    max_features: "sqrt"
    max_depth: 10
    random_state: 42
    n_jobs: -1

signal:
  z_window: 24
  z_threshold: 1
  atr_windows: { short: 4, long: 24 }
  atr_threshold: 0.9
  strategy_name: "zscore_atr_v1"

trading:
  enabled: True
  exec:
    symbol: "ETHUSDT"
    dualSidePosition: True
    use_balance_ratio: 0.95
    atr_period: 8
    atr_k: 1.5
    atr_k_tp: 1         # 新：止盈 1×ATR
    atr_k_sl: 1.5          # 新：止损 1.5×ATR
    slippage_ticks: 2
    max_position_close_retries: 5
    position_retry_sleep_sec: 0.5
  schedule:
    minute_at: 1
